name: Lint with Pylint

on:
  push:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint

      - name: Run Pylint and Show Score
        run: |
          pylint $(git ls-files '*.py') --exit-zero --score=y | tee pylint-report.txt
          SCORE=$(grep 'Your code has been rated at' pylint-report.txt | awk '{print $7}')
          echo "Pylint score: $SCORE"